### ISSUE TITLE
Will not connect to car and Apps check box missing.

### ISSUE THREAD

**Issue by JLedge81** [BimmerGestalt/AAIdrive#639]
Hey folks. I had an issue where my iDrive turned itself off & on and I had to perform a reset. Ever since, AAI will not connect & the apps check box is now missing under "device settings". Would anyone have any suggestions on how to rectify it please?

**Comment by Stjep10** [comment]
Same for me

**Comment by ogakul** [comment]
Here also connection unreliable since 2 days. I managed to fix it temporarly by disconnecting the phone in car settings, then starting the My BMW app and confirming all the agreements and reconnecting again. 

Maybe it has to do with the new My BMW app version 2.11.1 which was released some days ago? So a My BMW app downgrade to 2.9.3 could help until @hufman enhances AAIdrive support for My BMW version 2.11.1.

**Comment by JLedge81** [comment]
> Here also connection unreliable since 2 days. I managed to fix it temporarly by disconnecting the phone in car settings, then starting the My BMW app, confirming all the agreements and reconnecting again.
> 
> Maybe it has to do with the new My BMW app version 2.11.1 which was released some days ago? So a My BMW app downgrade to 2.9.3 could help until @hufman enhances AAIdrive support for My BMW version 2.11.1.

It sure is a strange issue. I can't even delete or forget the phones stored in the iDrive & the connected drive notifications have also stopped.

**Comment by KdiKomunismo** [comment]
Same here.
Tried to disconnect and reconnect but no luck

**Comment by HaivanJV** [comment]
Same here. Tried also My BMW 2.11.0 (current last is 2.11.1) and still not
working.
I think this might be something that BMW has to fix independently from the
app version.

Is there anyone with a working version of My Bmw?

**Comment by 6i6i** [comment]
For me it is working with the application 2.11.1 with HU NBT id 4

**Comment by Toskilabis** [comment]
> Hey gente. Tuve un problema en el que mi iDrive se apagó y encendió y tuve que realizar un reinicio. Desde entonces, AAI no se conectará y ahora falta la casilla de verificación de aplicaciones en "configuración del dispositivo". ¿Alguien tiene alguna sugerencia sobre cómo corregirlo, por favor?

Tengo el mismo problema. AAI ha dejado de funcionar con la última versión de la app My BMW

**Comment by Toskilabis** [comment]
> Hey folks. I had an issue where my iDrive turned itself off & on and I had to perform a reset. Ever since, AAI will not connect & the apps check box is now missing under "device settings". Would anyone have any suggestions on how to rectify it please?

I have the same problem. AAI has stopped working with the latest version of the My BMW app 2.11.1

**Comment by hufman** [comment]
Tracking MyBMW 2.11 is in #638 and not related to this issue, of the car losing its subscription status and not showing the Apps option.
Have you tried [manually refreshing the car's subscription status](https://www.reddit.com/r/BMW/comments/f8fn6n/comment/fkkwdsn/)? It should do it automatically within a day or two, and perhaps your issue has been resolved already.
If the car is having troubles letting you manage the paired devices, that sounds like something in the car might need to get reset harder, perhaps with a service center's help.

**Comment by Toskilabis** [comment]
> Tracking MyBMW 2.11 is in #638 and not related to this issue, of the car losing its subscription status and not showing the Apps option. Have you tried [manually refreshing the car's subscription status](https://www.reddit.com/r/BMW/comments/f8fn6n/comment/fkkwdsn/)? It should do it automatically within a day or two, and perhaps your issue has been resolved already. If the car is having troubles letting you manage the paired devices, that sounds like something in the car might need to get reset harder, perhaps with a service center's help.

Confirmed that it is a problem of version 2.11.1 of the My BMW app. I have reinstalled version 2.9.1, which you have at the following link, and everything is back to normal.

https://apkfun.com/es/down_My-BMW.40652332.html

**Comment by JLedge81** [comment]
> Tracking MyBMW 2.11 is in #638 and not related to this issue, of the car losing its subscription status and not showing the Apps option. Have you tried [manually refreshing the car's subscription status](https://www.reddit.com/r/BMW/comments/f8fn6n/comment/fkkwdsn/)? It should do it automatically within a day or two, and perhaps your issue has been resolved already. If the car is having troubles letting you manage the paired devices, that sounds like something in the car might need to get reset harder, perhaps with a service center's help.

Thank you. So my car had unlimited subscription to connected drive, but I have booked it in with BMW for some warranty work, so I will see what happens there.

**Comment by Sza5wz12** [comment]
Hi.  My aaidrive stopped working after my connected drive subscription ended.  I have a G20 with ID6.  Apps in connected drive are gone and now aaidrive can't connect.  Is there any option to use aaidrive without a Connected drive subscription? I checked that it is not caused by the new version of My BMW.  I have installed the latest version and an older one, the result is the same.  Aaidrive stopped working on the exact day the subscription ended. Thanks for the help.

**Comment by JLedge81** [comment]
> 
> Confirmed that it is a problem of version 2.11.1 of the My BMW app. I have reinstalled version 2.9.1, which you have at the following link, and everything is back to normal.
> 
> https://apkfun.com/es/down_My-BMW.40652332.html

Just a quick update. Going back to 2.9.1 did not solve the problem for me, but thanks for the suggestion.

**Comment by HaivanJV** [comment]
About the subscription status: I went into my Connected Drive profile page to check mine.
I should have unlimited coverage with "connected drive service" and "remote services"
The first seems the closer of what we require to have the Apps working.
There is also an extra package called "Connected+" which I have booked until Apr 2023.

Do any of you know if there is a "service status" page for such services?

<img width="898" alt="image" src="https://user-images.githubusercontent.com/22883596/206112721-52690590-8f5e-4f7e-895d-03914292893f.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/22883596/206113055-8d6b55ac-fd7b-43b8-9da3-69376364ef61.png">

**Comment by hufman** [comment]
@Sza5wz12 as far as I know, the Apps functionality required for AAIdrive can only be added with a subscription or with coding techniques. My Mini has it coded from the factory and doesn't offer any subscription services, so I'm not certain exactly which subscription is needed.
@HaivanJV I _think_ it only needs ConnectedDrive and not Connected+, a vague memory from previous emails with other users. BMW offers different services in different regions, further confusing things :)
@JLedge81 I hadn't expected the app version to affect it, hopefully your service appointment will fix things up!

**Comment by ogakul** [comment]
In my case the issue seems to have been fixed by one of these things but I can't say which one exactly, so here is everything I had done while troubleshooting:
- relogging into My BMW 2.11.1
- making sure all agreements in My BMW accepted
- making surecar stats visible in My BMW app
- delete BT connection to the phone in the car and reconnect AAIdrive by initiating connection from car and selecting "Apps"
- delete BT connection to the phone in the car and reconnect AAIdrive by initiating connection from car and selecting "Phone"
- check permissions of AAIdrive and My BMW on the phone: Both need Nearby Devices permission

**Comment by HaivanJV** [comment]
Tried everything of the above with one addition: I connected the Apps via USB and everything worked immediately, AAidrive included.

This has more the looks of a major problem with the Bluetooth connection between idrive (mine is ID6) and My BMW app, with the additional complication that it is not sensitive of which version of the My BMW app is installed.

I tried to email the connected drive support, but I have low expectations there... ![IMG_20221207_214322.jpg](https://user-images.githubusercontent.com/22883596/206295358-f0c2dcb8-3d88-493a-8abd-6a7ea3cbf3ff.jpg)

**Comment by hufman** [comment]
Again, this thread is about the Apps option disappearing entirely from the car. Please move discussion about inability to connect to an activated car to the other issue.

**Comment by KdiKomunismo** [comment]
Hi everyone, I have an update that could be useful to everyone.
Brief recap:
I use AAIdrive for Android, last version from Play Store, My BMW for Android, last version from Play Store, on a 2018 BMW 418d with ID6L, with an active subscription to connected+ program. 
After updating My BMW to last version my first symptom was the inability to use AAIdrive, but then I noticed a couple more. First, as already pointed out, I don't see the App option in my car's phone connection, but second, I cannot send a destination from the app to the car anymore. For the rest of the remote functions (door lock, lights, etc) the app-car connection works, but when I try to send one destination to the car the notification just doesn't appear, despite being sent from the app. Also, car's location in the app is updated only when I turn on the car, then it just stay there for the whole trip, until I shut down the car and turn it on again.
I reached out to BMW assistance today and it seems like they have noticed the problem on a bunch of cars with the same operating system. The resolution of the issue has been rescheduled for the end of March, from the end of November it was before.
Only positive side, they told me that I could ask for a reimbursement of the connected+ if the solution takes too long.

**Comment by HaivanJV** [comment]
@KdiKomunismo I have all the same symptoms as yours, with only USB coming to help (not how I would solve though).

BMW assistance hasn't reply to me yet. I was curious though: this has all the sounds to be a ID6L specific problem, not MyBmw App version related/ not phone-android related/ neither for other idrive versions (i.e. for Mini). Do you have the feeling that this is clear from the answer they gave you?

March is quite far. Incredibly long times to bug fix something centrally...

**Comment by KdiKomunismo** [comment]
I'm totally sure it is a ID6L related problem.
Haven't tried USB connection yet, I'll give it a try.

**Comment by fookyuanloh** [comment]
Question for @hufman 
What should we see on the MyBMW app, in order to confirm that is connected to the car?
ie: When I use USB, phone prompts me whether to allow sharing/access to data
Without USB (wireless) I don't even know whether the MyBMW app is connected

How can we confirm that?

**Comment by hufman** [comment]
The MyBMW or Mini notification will change, from saying "Bluetooth connection is established" to "MINI App is connected to vehicle".
![image](https://user-images.githubusercontent.com/1592375/208008040-1c41f5db-ebe8-4029-8c02-699f87a08a91.png) ![image](https://user-images.githubusercontent.com/1592375/208008085-b07bd26c-f0c5-41ad-ba0a-af8baced6838.png)

Your MyBMW or Mini app should have a Info section with a Device Connection line that shows the following screen:
![image](https://user-images.githubusercontent.com/1592375/208008493-384832ec-eeb7-4525-a065-a80983adbeb4.png) ![image](https://user-images.githubusercontent.com/1592375/208008581-5d1f574f-9587-4ad5-bec2-b1fed41636e3.png)

But again, this issue is about this person's car losing Apps subscription, perhaps you meant to comment on #638 about MyBMW 2.11.1 Bluetooth connections?

**Comment by Toskilabis** [comment]
I have tried version 2.12 and still have the same problems as in version 2.11. So I reinstall version 2.09 and everything goes back to normal, everything works correctly.

**Comment by Aro320x** [comment]
> > Tracking MyBMW 2.11 befindet sich in #638 und hat nichts mit diesem Problem zu tun, bei dem das Auto seinen Abonnementstatus verliert und die Apps-Option nicht angezeigt wird. Haben Sie versucht [, den Abonnementstatus des Autos manuell zu aktualisieren](https://www.reddit.com/r/BMW/comments/f8fn6n/comment/fkkwdsn/) ? Es sollte dies automatisch innerhalb von ein oder zwei Tagen tun, und vielleicht wurde Ihr Problem bereits gelöst. Wenn das Auto Probleme hat, Sie die gekoppelten Geräte verwalten zu lassen, klingt das so, als müsste etwas im Auto möglicherweise schwieriger zurückgesetzt werden, möglicherweise mit der Hilfe eines Servicecenters.
> 
> Bestätigt, dass es sich um ein Problem der Version 2.11.1 der My BMW App handelt. Ich habe Version 2.9.1 neu installiert, die Sie unter folgendem Link haben, und alles ist wieder normal.
> 
> https://apkfun.com/es/down_My-BMW.40652332.html

I can only confirm!
After updating the My BMW app, no more app connection via Bluetooth.
Have tried many things.
The only thing that worked is to reinstall version 2.9.1. Thus, everything works normally again, as before!

**Comment by LACNR** [comment]
Considering he said he had to do a reset, try to update your BMW Services, the location can be different depending on your iDrive Version. But usually can be found at least in the ConnectedDrive Menu, then pressing the Option Button of your iDrive Controller. Serveral Options should pop-up, selecting Update BMW Services.

Additionally, you can search for a new Version for your Cars OS on https://www.bmw.com/en/footer/software-updates.html scroll down and enter your VIN. If you have Remote Updates suported in-car, you can run Remote Update from your cars iDrive available since ID7 (maybe ID6 as well)

**Comment by KdiKomunismo** [comment]
I quick update.
I got back to My BMW 2.9.3 and now everything works perfectly again.

Il mer 28 dic 2022, 08:41 LACNR ***@***.***> ha scritto:

**Comment by Aro320x** [comment]
> BMW services update has brought me nothing!!!
The only thing that helped was to reinstall version 2.9.1, so everything works normally again, as before!

Remote updates only from Operating System 7! 
(Whether your vehicle is eligible for the BMW Remote Software Upgrade depends on the hardware installed in your vehicle. Almost all vehicles with BMW Operating System 7 and 8 are capable of this.

You can easily determine yourself whether your vehicle is one of them. To do this, select the following in the vehicle menu: "My Vehicle" > "Settings" > "General Settings" > "Remote Software Upgrade". If "Remote Software Upgrade" is displayed, you can use this function).

**Comment by LACNR** [comment]
> > BMW services update has brought me nothing!!!
> > The only thing that helped was to reinstall version 2.9.1, so everything works normally again, as before!
> 
> Remote updates only from Operating System 7! (Whether your vehicle is eligible for the BMW Remote Software Upgrade depends on the hardware installed in your vehicle. Almost all vehicles with BMW Operating System 7 and 8 are capable of this.
> 
> You can easily determine yourself whether your vehicle is one of them. To do this, select the following in the vehicle menu: "My Vehicle" > "Settings" > "General Settings" > "Remote Software Upgrade". If "Remote Software Upgrade" is displayed, you can use this function).

Yeah I wasn't sure if 6 could do it already via Remote. Did you then try from the link I provided which will if Updates are available allow you to download the new Software Update, check frequently as it may have serveral updates for your vehicle (a new Update doesn't include the other updates) be aware to follow instructions to download it on a USB Stick and then install it via the car interface - Settings - Software Update -  Update Software. The Updates usually expand functions and compatibility with phones, fixed bugs and improved overall functionality and various features.

**Comment by Aro320x** [comment]
Yes I have installed the latest USB software from BMW. There is no newer version for my model!
Whether it is specifically on my phone, I do not think. Since all functions work in the new and old "my Bmw App"! I can see fuel level, position and status. Also the activation of the auxiliary heating works!

**Comment by JLedge81** [comment]
*UPDATE - Resolved*
Car has just had the iDrive basic settings reinstalled at the dealer and AAI is now working again. Thanks for all your input folks.

**Comment by hufman** [comment]
I'm glad to hear it :D

**Comment by Aro320x** [comment]
> Das freut mich zu hören :D

Hmm...
And that means now that the problem is solved for all parties involved...???
I do not understand...?
So now I should go to BMW service and give them the order "to reinstall the iDrive basic settings"...?
Reason... I have an app that suddenly no longer works...?
This is illogical for me!

**Comment by LACNR** [comment]
Well, technically the issue is solved for the original author. It doesn't seem to be a generel problem (I don't have any difficulties with the latest and previous MyBMW App and AADrive. By the way by now MyBMW has released 2.12 or 2.13? a few weeks ago maybe it helps for lost of you?

Technically, anyone can do a reset within the car question is if it is needed but restore basic settings is always possible, question is are we talking about the iDrive profile Settings, a system reboot or hard-reset to default factory software.

**Comment by Aro320x** [comment]
> 

Oh that's right. Had I overlooked that it was the original author!
Thanks for the quick reply and the reference that there is now already the version 2.12 or 2.13!

I will try on occasion times whether with the new version also my problems are fixed!

That with the iDrive profile reset within the car, I have made several times.
But has not brought any changes.

**Comment by hufman** [comment]
Yes, JLedge81's problem of the car forgetting its lifetime activation for the Apps feature and removing the Apps checkbox entirely was resolved by the dealer reloading the factory settings.
The unrelated issue of MyBMW not connecting to the car after version 2.9 is primarily discussed in #638, please subscribe to that discussion.

**Comment by fookyuanloh** [comment]
Sorry to budge in
Any other  way to reload configuration by ourselves?

TBH I've never successfully connect via BT to the MyBMW app
Not even to the point I can see fuel info etc on it

I have lifetime ConnectedDrive subscription as well
Even with USB, I don't get fuel info

I asked the dealer in Malaysia, all claim it is normal, which I think is
not right

**Comment by LACNR** [comment]
> Sorry to budge in Any other way to reload configuration by ourselves? TBH I've never successfully connect via BT to the MyBMW app Not even to the point I can see fuel info etc on it I have lifetime ConnectedDrive subscription as well Even with USB, I don't get fuel info I asked the dealer in Malaysia, all claim it is normal, which I think is not right
> […](#)

Bluetooth Connection and availability of the MyBMW App functions depends on the model year of your car. While MyBMW is build to support models build from 2014+, specific functions may not be supportedavailable anymore by MyBMW depending on your production year and country. Sad to know, that the old apps BMW Connected Classic and BMW Connected could show fuel level and estimated mileage from models 2012+ via USB and Bluetooth. For some reason, the MyBMW App doesn't use the same method to read the information.

Bluetooth Apps was a feature that was available around production year 2017+ although if you had a specific opitions equipped in your car (e.g. enhanced bluetooth connection) it may work with modes build 2015+. So yes, your dealer can be right, you can read the terms of the app on the App Store. They specifically mention that not all functions are available with each car depending on your car, production year, options and country.
